### ISSUE TITLE
Not working with SDK 6.0.0

### ISSUE THREAD

**Issue by PietroGranati** [viezel/NappDrawer#199]
As titanium guidelines the module must be recompiled with minimum SDK

**Comment by NLKok** [comment]
+1

**Comment by macCesar** [comment]
+1

**Comment by Max87ZA** [comment]
Can somebody compile it with new SDK? Thanks

**Comment by MarkBoyer** [comment]
I have done a simple recompile, I have done VERY minimal testing, there is no warrantee given or implied, but if you would like to download this version and TEST IT HEAVILY, feel free...

https://github.com/MarkBoyer/Appcelerator-Modules

I am by no means attempting to take any credit, and I am by no means a Java developer, but like many, I rely HEAVILY on this module in my Appcelerator development.

**Comment by hopstad** [comment]
MarkBoyer : Thanks for your fix, but Im affraid it crashed my app. It works by dragging, but opening from a toggleLeftWindow() crashed it.

**Comment by MarkBoyer** [comment]
@hopstad - Is it possible there's something else going on with the crash?  I only ask because I went back and tested again using the Genymotion simulator and it works with Android 5.1.0 and 6.0.0 for me using both the swipe and toggleLeftWindow.  I do use Fokke's widget interface but that shouldn't make a difference.

**Comment by hopstad** [comment]
I have a rather large and complex app so it might be something else causing it. But it's weird it's working fine with the old version.

I'll look more into it tomorrow. Thanks

On Dec 1, 2016 6:11 PM, MarkBoyer <notifications@github.com> wrote:

@hopstad<https://github.com/hopstad> - Is it possible there's something else going on with the crash? I only ask because I went back and tested again using the Genymotion simulator and it works with Android 5.1.0 and 6.0.0 for me using both the swipe and toggleLeftWindow. I do use Fokke's widget interface but that shouldn't make a difference.
